# 컴퓨터들
services:

  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/myfolder/frontend/src
      - ./frontend/public:/myfolder/frontend/public
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
