FROM node:20

COPY ./package.json /myfolder/backend/
COPY ./yarn.lock /myfolder/backend/
WORKDIR /myfolder/backend
RUN yarn install --production

COPY . /myfolder/backend/

RUN yarn build
CMD yarn start:prod
